---
title: "First Knit"
author: "Jonathan Campos"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended William J Pete Knight High school and graduated from there. It was very fun and a great environment . Math is for sure way easier for me.English is to many rules and to neady for me. I would say lunch is my favorite subject. But all jokes aside I would say physics I did best in. Just because that was the best teacher ive ever had. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have a windows pc I use at home. It runs pretty good I think it is very suitable for this class. I would say on a scale from 1-10 I am atleast an 8 for technology.I do have internet acess at home and it is very great.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
  I prefer people to call me Jonathan, and my buddys call me Jonathan As well. 
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
  I want to be healthy and wealthy, that is my life goal. I think business and management is a subject I am really interested in or economics because of money aspect to it. I will get my masters in Radiology and become an X-Ray Technician.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
No I have not gone to any foreign countries. If I were to go to any I would love to go to France.  No I have never served in the military, Which ever is the easiest and am least likely to die.    
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




